### ISSUE TITLE
Review back button from browser

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#314] opened 2019-05-07 00:09 UTC
Please review back button from browser, because everything went blank and I couldn't see the survey anymore when I clicked on the back button. 
Using Google chrome

**Comment by javierpf** [comment] 2019-05-08 02:09
@aprojas Can you provide steps to reproduce this bug?

**Comment by stacylorraineprendeville** [comment] 2019-05-09 14:26
@javierpf another option here would be to disable the back button in the browser - as we have the back button in the screen and we are "in flow" (not an 80´s period reference but in a flow within a seperate window page) - This is ok for UX and I imagine less of a pain?

**Comment by javierpf** [comment] 2019-05-09 14:33
Actually, what I meant in the previous comment is that the browser's back button is working fine, so I could not reproduce the problem @aprojas described. 
Do you also notice some kind of unexpected behavior with the back button or history navigation in general @stacylorraineprendeville ?

**Comment by stacylorraineprendeville** [comment] 2019-05-10 23:33
@javierpf I created one issue for a minor issue with the back button  - but in general seems fine so I am closing this.

**Closed by stacylorraineprendeville** 2019-05-10 23:33 UTC
Labels: high priority, question
