### ISSUE TITLE
Colours behind images in indicators

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#362] opened 2019-05-11 00:19 UTC
Please add the colour behind the indicators - aesthetically as the page loads this would look better![Screen Shot 2019-05-10 at 20.17.30.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/24289eed-8537-4440-b3ca-0134d042701b)

**Comment by gonzarodriguezt** [comment] 2019-05-11 00:34
Duplicate of #358, created it after the sprint review

**Closed** 2019-05-11 19:41 UTC
