### ISSUE TITLE
Bug: saving and going back in indicators section

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#197] opened 2019-03-14 20:06 UTC
@aprojas commented on [Mon Mar 11 2019](https://github.com/FundacionParaguaya/FP-PSP-SERVER/issues/500)

After writing down my 5 priorities, I clicked on continue but before saving and closing, I went back to change the level of the last indicator. when I arrived to the indicators list again, my priorities remained the same, but I could not continue because it said that I didn't have my 5 priorities chosen. So, in the end, I had 10 priorities.

**Comment by Danman7** [comment] 2019-04-04 11:48
Duplicate of #198

**Closed by Danman7** 2019-04-04 11:48 UTC
Labels: duplicate
