### ISSUE TITLE
Ecuador and Fusai Survey don't work

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#236] opened 2019-04-08 15:06 UTC
When trying to take the surveys of Ecuador and Fusai, I clicked on them and this blank page appeared. 
![2019-04-05.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/d83178fb-bc47-4e47-96e5-54140cfb4955)

**Comment by stacylorraineprendeville** [comment] 2019-04-17 12:52
@aprojas We need to know the credentials you logged in with to resolve this issue.

**Comment by aprojas** [comment] 2019-04-17 12:54
It's demo/demo @stacylorraineprendeville

**Comment by Danman7** [comment] 2019-04-17 13:08
@aprojas I'm unable to reproduce. I log into https://testing.povertystoplight.org/ with the demo account and can take both surveys. Ecuador is missing terms and privacy and Fusai is missing terms, but I can skip that with the Agree button. Can you provide steps to reproduce?

**Comment by stacylorraineprendeville** [comment] 2019-04-17 13:36
Closed as non- reproducible......

**Closed by stacylorraineprendeville** 2019-04-17 13:36 UTC
Labels: bug, cannot reproduce, high priority
